### ISSUE TITLE
maizzle cli fails when using es modules

### ISSUE THREAD

**Issue by mariosant** [maizzle/cli#174]
Hi there! Thanks for all the effort on maizzle!

maizzle cli fails when `"type": "module"` is being used in `package.json`.

Example `package.json`:
```
{
  "private": true,
  "type": "module",
  "scripts": {
    "start": "maizzle serve"
  },
  "dependencies": {
    "@maizzle/framework": "latest"
  }
}
```

```
$ npm start
/xxxx/node_modules/@maizzle/framework/src/generators/config.js:26
        throw new Error(`could not load config.${env}.js`)
    Error: could not load config.production.js
    at Object.getMerged (/xxxx/node_modules/@maizzle/framework/src/generators/config.js:26:15)
    at Object.serve (/xxxx/node_modules/@maizzle/framework/src/commands/serve.js:24:18)
    at Command.<anonymous> (/xxxx/node_modules/@maizzle/cli/src/index.js:75:24)
    at Command.listener [as _actionHandler] (/xxxx/node_modules/commander/lib/command.js:482:17)
    at /xxxx/node_modules/commander/lib/command.js:1265:65
    at Command._chainOrCall (/xxxx/node_modules/commander/lib/command.js:1159:12)
    at Command._parseCommand (/xxxx/node_modules/commander/lib/command.js:1265:27)
    at /xxxx/node_modules/commander/lib/command.js:1063:27
    at Command._chainOrCall (/xxxx/node_modules/commander/lib/command.js:1159:12)
    at Command._dispatchSubcommand (/xxxx/node_modules/commander/lib/command.js:1059:23)
```

**Comment by cossssmin** [comment]
Hi, Maizzle is not currently ESM compatible.

**Comment by mariosant** [comment]
Cool, it works great as an api running on node@18 and es modules enabled. Closing this ticket as it's working as intended atm.
