### ISSUE TITLE
updateNotifier breaking `maizzle build` (--bin, monorepo)

### ISSUE THREAD

**Issue by michalvadak** [maizzle/cli#204]
- @maizzle/framework: 4.4.4
- Node.js Version: 16.13.0

After running `maizzle build en --bin ../../../node_modules/@maizzle/framework/src`

```
✔ Built 2 templates in 0.229s
node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module './node_modules/@maizzle/framework/package.json'
Require stack:
- /Users/.../libs/web/email/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolveFileName (/Users/.../node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/.../node_modules/resolve-from/index.js:43:9)
    at module.exports (/Users/.../node_modules/resolve-from/index.js:46:47)
    at module.exports (/Users/.../node_modules/import-from/index.js:4:55)
    at module.exports (/Users/.../node_modules/import-cwd/index.js:4:30)
    at Command.<anonymous> (/Users/.../node_modules/@maizzle/framework/node_modules/@maizzle/cli/src/index.js:52:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/.../libs/web/email/noop.js' ]
}
```

I've looked into https://github.com/maizzle/framework/issues/974 and https://github.com/maizzle/cli/issues/198 but doesn't managed to get it to work. I have only installed `@maizzle/framework`.

I am using [Nx monorepo](https://nx.dev/).

**Comment by michalvadak** [comment]
Sorry for the delay... I've updated to `"@maizzle/framework": "^4.4.5"` also the `"@maizzle/cli": "^1.5.6"` and still getting the same error

```
maizzle build en
node:internal/modules/cjs/loader:1026
  const err = new Error(message);
              ^

Error: Cannot find module './node_modules/@maizzle/framework/src'
Require stack:
- /Users/michalvadak/GeekCoders/gc-web/libs/web/email/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at resolveFileName (/Users/michalvadak/GeekCoders/gc-web/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/michalvadak/GeekCoders/gc-web/node_modules/resolve-from/index.js:43:9)
    at module.exports (/Users/michalvadak/GeekCoders/gc-web/node_modules/resolve-from/index.js:46:47)
    at module.exports (/Users/michalvadak/GeekCoders/gc-web/node_modules/import-from/index.js:4:55)
    at module.exports (/Users/michalvadak/GeekCoders/gc-web/node_modules/import-cwd/index.js:4:30)
    at Command.<anonymous> (/Users/michalvadak/GeekCoders/gc-web/node_modules/@maizzle/cli/src/index.js:49:13)
    at Command.listener [as _actionHandler] (/Users/michalvadak/GeekCoders/gc-web/node_modules/@maizzle/cli/node_modules/commander/lib/command.js:482:17)
    at /Users/michalvadak/GeekCoders/gc-web/node_modules/@maizzle/cli/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/michalvadak/GeekCoders/gc-web/node_modules/@maizzle/cli/node_modules/commander/lib/command.js:1177:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/michalvadak/GeekCoders/gc-web/libs/web/email/noop.js' ]
}
```

**Comment by cossssmin** [comment]
That error is different though, it's not finding the framework entry point now instead of `package.json`. 

Make sure to specify the `--bin` option like before, I see you ran it without it this time :)

**Comment by michalvadak** [comment]
Even with `--bin` I've got the error

```
 maizzle build en --bin ../../../node_modules/@maizzle/framework
✔ Built 2 templates in 0.386s
node:internal/modules/cjs/loader:1026
  const err = new Error(message);
              ^

Error: Cannot find module './node_modules/@maizzle/framework/package.json'
Require stack:
- /Users/michalvadak/GeekCoders/gc-web/libs/web/email/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at resolveFileName (/Users/michalvadak/GeekCoders/gc-web/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/michalvadak/GeekCoders/gc-web/node_modules/resolve-from/index.js:43:9)
    at module.exports (/Users/michalvadak/GeekCoders/gc-web/node_modules/resolve-from/index.js:46:47)
    at module.exports (/Users/michalvadak/GeekCoders/gc-web/node_modules/import-from/index.js:4:55)
    at module.exports (/Users/michalvadak/GeekCoders/gc-web/node_modules/import-cwd/index.js:4:30)
    at Command.<anonymous> (/Users/michalvadak/GeekCoders/gc-web/node_modules/@maizzle/cli/src/index.js:52:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/michalvadak/GeekCoders/gc-web/libs/web/email/noop.js' ]
}
```

**Comment by michalvadak** [comment]
@cossssmin Any updates?

**Comment by michalvadak** [comment]
@cossssmin Hey, any updates?

**Comment by cossssmin** [comment]
Hmm not sure what causes it, does it work if given an absolute path?

**Comment by michalvadak** [comment]
Does not work even if given absolute path.

I'm using Nx monorepo (https://nx.dev/) so my file structure is.

```
libs
  -web
   -email
    ...
  -shared
    ...
node_modules
```


I'm running this command ` maizzle build en --bin ../../../node_modules/@maizzle/framework`  from the `email` folder and that results in this error:
```
email git:(email) ✗ maizzle build en --bin ../../../node_modules/@maizzle/framework
✔ Built 2 templates in 0.256s
node:internal/modules/cjs/loader:1026
  const err = new Error(message);
              ^

Error: Cannot find module './node_modules/@maizzle/framework/package.json'
Require stack:
- /Users/michalvadak/GeekCoders/gc-web/libs/web/email/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at resolveFileName (/Users/michalvadak/GeekCoders/gc-web/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/Users/michalvadak/GeekCoders/gc-web/node_modules/resolve-from/index.js:43:9)
    at module.exports (/Users/michalvadak/GeekCoders/gc-web/node_modules/resolve-from/index.js:46:47)
    at module.exports (/Users/michalvadak/GeekCoders/gc-web/node_modules/import-from/index.js:4:55)
    at module.exports (/Users/michalvadak/GeekCoders/gc-web/node_modules/import-cwd/index.js:4:30)
    at Command.<anonymous> (/Users/michalvadak/GeekCoders/gc-web/node_modules/@maizzle/cli/src/index.js:52:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/michalvadak/GeekCoders/gc-web/libs/web/email/noop.js' ]
}
```

I even updated to "@maizzle/framework": "^4.5.0"
